---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

platform:
  os: linux
  arch: arm64

workspace:
  path: /drone/src/epsilon-language-server

steps:
- name: Build jar
  image: maven:3.8.7
  commands:
  - git clone https://gitea.home.pi/Frinksy/epsilon-static-analysis.git /drone/src/epsilon-static-analysis
  - cd /drone/src/epsilon-static-analysis/org.eclipse.epsilon.eol.staticanalyser/
  - mvn clean install
  - cd /drone/src/epsilon-language-server/
  - mvn package

